[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "dist"
  autoLaunch = true

# Redirect all API requests to our Netlify function
[[redirects]]
  from = "/.netlify/functions/analytics-api/*"
  to = "/.netlify/functions/analytics-api"
  status = 200
  force = true

# For SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
